# Étape 1 : build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["DeckMicroservice/DeckMicroservice.csproj", "DeckMicroservice/"]
RUN dotnet restore "DeckMicroservice/DeckMicroservice.csproj"
COPY . .
RUN dotnet publish "DeckMicroservice/DeckMicroservice.csproj" -c Release -o /app/publish

# Étape 2 : runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
RUN apt-get update && apt-get install -y curl
EXPOSE 5003
ENTRYPOINT ["dotnet", "DeckMicroservice.dll"]