# Étape 1 : build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["GameMicroservice/GameMicroservice.csproj", "GameMicroservice/"]
RUN dotnet restore "GameMicroservice/GameMicroservice.csproj"
COPY . .
RUN dotnet publish "GameMicroservice/GameMicroservice.csproj" -c Release -o /app/publish

# Étape 2 : runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
RUN apt-get update && apt-get install -y curl
EXPOSE 5004
ENTRYPOINT ["dotnet", "GameMicroservice.dll"]